reddit:
  enabled: True
  info: False
  image: True
  video: True
instagram:
  enabled: True
  info: False
  image: True
  thumbnail: False
  video: True
youtube:
  enabled: True
  info: False
  thumbnail: False
  video: True
  tmp_path: "/data/tmp/"
tiktok:
  enabled: True
  video: True
respond_to_notice: False
